### ISSUE TITLE
current svn version (r1034) does not compile on Ubuntu 12.04 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sbmbeng/tesseract-ocr#1080]
```
What steps will reproduce the problem?
1.checkout the svn-Version (r1034)
2.run ./autogen.sh, ./configure
3.make

What is the expected output? What do you see instead?
Error while running make:

pdfrenderer.cpp: In static member function 'static bool 
tesseract::TessPDFRenderer::pixToPDFObj(Pix*, long int, char**, long int*)':
pdfrenderer.cpp:524:7: error: 'cid' was not declared in this scope
pdfrenderer.cpp:558:36: error: 'cid' was not declared in this scope
pdfrenderer.cpp: In member function 'virtual bool 
tesseract::TessPDFRenderer::BeginDocumentHandler()':
pdfrenderer.cpp:380:29: warning: ignoring return value of 'size_t fread(void*, 
size_t, size_t, FILE*)', declared with attribute warn_unused_result 
[-Wunused-result]
make[2]: *** [libtesseract_api_la-pdfrenderer.lo] Fehler 1
make[2]: Verlasse Verzeichnis '/home/.../Tesseract/tesseract-ocr/api'
make[1]: *** [all-recursive] Fehler 1
make[1]: Verlasse Verzeichnis '/home/.../Tesseract/tesseract-ocr'

What version of the product are you using? On what operating system?
tessearct svn r1034, Ubuntu 12.04.3 one 64 bit AMD machine

Please provide any additional information below.
pdfrenderer.cpp was added in r963, there have been some minor changes to it.
```

Original issue reported on code.google.com by `hanksch...@googlemail.com` on 30 Jan 2014 at 2:58
