### ISSUE TITLE
tesseract-2.03 does not compile on Ubuntu Linux 8.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sbmbeng/tesseract-ocr#177]
```
What steps will reproduce the problem?
1. download tesseract-2.03 source
2. extract
3. attempt to compile...

What is the expected output? What do you see instead?

Making all in viewer
make[2]: Entering directory `/home/andrew/Desktop/tesseract-2.03/viewer'
make[3]: Entering directory `/home/andrew/Desktop/tesseract-2.03/viewer'
g++ -DHAVE_CONFIG_H -I. -I. -I..     -g -O2 -c scrollview.cpp
scrollview.cpp: In member function ‘SVEvent* SVEvent::copy()’:
scrollview.cpp:62: error: ‘strlen’ was not declared in this scope
scrollview.cpp:63: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In static member function ‘static void*
ScrollView::MessageReceiver(void*)’:
scrollview.cpp:89: error: ‘strlen’ was not declared in this scope
scrollview.cpp:107: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In static member function ‘static void*
ScrollView::StartEventHandler(void*)’:
scrollview.cpp:302: error: ‘INT_MAX’ was not declared in this scope
scrollview.cpp: In member function ‘char* ScrollView::ShowInputDialog(const
char*)’:
scrollview.cpp:689: error: ‘strlen’ was not declared in this scope
scrollview.cpp:690: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In member function ‘char* ScrollView::AddEscapeChars(const
char*)’:
scrollview.cpp:795: error: ‘strchr’ was not declared in this scope
scrollview.cpp:800: error: ‘strncpy’ was not declared in this scope
scrollview.cpp:807: error: ‘strlen’ was not declared in this scope
scrollview.cpp:807: error: ‘strncpy’ was not declared in this scope
make[3]: *** [scrollview.o] Error 1
make[3]: Leaving directory `/home/andrew/Desktop/tesseract-2.03/viewer'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/andrew/Desktop/tesseract-2.03/viewer'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/andrew/Desktop/tesseract-2.03'
make: *** [all-recursive-am] Error 2



What version of the product are you using? On what operating system?

tesseract-2.03 source. Ubuntu Linux 8.10. Gcc 4.2 is installed, also gcc
4.3. I am going to assume it defaults to using 4.3. Would using an older
gcc version work?



```

Original issue reported on code.google.com by `keen...@gmail.com` on 16 Dec 2008 at 6:40
