### ISSUE TITLE
Build failed: symbols not declared

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sbmbeng/tesseract-ocr#147]
```
tesseract 2.03 fails to build with gcc 4.3.1 and complains about symbols 
not declared:

<SNIP>
make[3]: Leaving directory `/tmp/tesseract-2.03/textord'
make[2]: Leaving directory `/tmp/tesseract-2.03/textord'
Making all in viewer
/tmp/tesseract-2.03/viewer
make[2]: Entering directory `/tmp/tesseract-2.03/viewer'
make[3]: Entering directory `/tmp/tesseract-2.03/viewer'
g++ -DHAVE_CONFIG_H -I. -I. -I..     -g -O2 -c scrollview.cpp
scrollview.cpp: In member function ‘SVEvent* SVEvent::copy()’:
scrollview.cpp:62: error: ‘strlen’ was not declared in this scope
scrollview.cpp:63: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In static member function ‘static void* 
ScrollView::MessageReceiver(void*)’:
scrollview.cpp:89: error: ‘strlen’ was not declared in this scope
scrollview.cpp:107: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In static member function ‘static void* 
ScrollView::StartEventHandler(void*)’:
scrollview.cpp:302: error: ‘INT_MAX’ was not declared in this scope
scrollview.cpp: In member function ‘char* 
ScrollView::ShowInputDialog(const char*)’:
scrollview.cpp:689: error: ‘strlen’ was not declared in this scope
scrollview.cpp:690: error: ‘strncpy’ was not declared in this scope
scrollview.cpp: In member function ‘char* 
ScrollView::AddEscapeChars(const char*)’:
scrollview.cpp:795: error: ‘strchr’ was not declared in this scope
scrollview.cpp:800: error: ‘strncpy’ was not declared in this scope
scrollview.cpp:807: error: ‘strlen’ was not declared in this scope
scrollview.cpp:807: error: ‘strncpy’ was not declared in this scope

[note: there are also other files that fails to compile]

The reason is http://www.cyrius.com/journal/2007/05/10#gcc-4.3-include , 
IMHO. Attached patch fixes the problem for my setup.

What steps will reproduce the problem?
1. Download tesseract-2.03
2. ./configure
3. make (using gcc 4.3.1, openSUSE 11.0)

What is the expected output? What do you see instead?
* It should compile. It does not compile.

What version of the product are you using? On what operating system?
* tesseract 2.03 with, openSUSE 11.0, x86-64, gcc 4.3.1

```

Original issue reported on code.google.com by `uzel...@gmail.com` on 6 Aug 2008 at 12:14

Attachments:
- [tesseract-2.03-includes-fix.patch](https://storage.googleapis.com/google-code-attachments/tesseract-ocr/issue-147/comment-0/tesseract-2.03-includes-fix.patch)
