### ISSUE TITLE
 leptonica_pageseg.cpp fails to compile in 2.02

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sbmbeng/tesseract-ocr#98]
```
What steps will reproduce the problem?
1. runautoconf; ./configure; makeleptonica_pageseg.cpp:32:24: error: 
2.
3.

What is the expected output? What do you see instead?
allheaders.h: No such file or directory

and then numerous other error

What version of the product are you using? On what operating system?
2.02; ubuntu 7.02

Please provide any additional information below.

```

Original issue reported on code.google.com by `drdunk.g...@gmail.com` on 2 Mar 2008 at 4:45
